apiVersion: v1
kind: Service
metadata:
  name: {{ include "restic-backup-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "restic-backup-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "restic-backup-operator.selectorLabels" . | nindent 4 }}
