name: Cleanup Old Docker Images

on:
  schedule:
    # Run weekly on Sunday at 3:00 UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

env:
  RETENTION_DAYS: 30

permissions:
  packages: write

jobs:
  cleanup:
    name: Delete Old Commit-Hash Images
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup ghcr.io images
        uses: snok/container-retention-policy@v3
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ github.event.repository.name }}
          cut-off: ${{ env.RETENTION_DAYS }}d
          keep-n-most-recent: 3
          filter-tags: '[0-9a-f]{40}'
          tag-selection: filtered
